version: "3.7"

services:

  osu-server:
    build: ./
    ports:
      - 8080:80
    depends_on:
      - mysql
    networks:
      - db-network

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - "MYSQL_DATABASE=osu"
      - "MYSQL_USER=osu-user"
      - "MYSQL_PASSWORD=test"
      - "MYSQL_ROOT_PASSWORD=rootpasswd"
    networks:
      - db-network

networks:
  db-network:
